@startuml

left to right direction

actor Customer as c

rectangle "Restaurant Ordering System" {

  usecase "Scan QR" as scan_qr
  usecase "Choose Table" as choose_table
  usecase "Place Order" as place_order
  usecase "Track Order Status" as track_order
  usecase "View Table" as view_table
  usecase "View Menu" as view_menu

  usecase "Accept Order" as accept_order
  usecase "Reject Order" as reject_order
  usecase "Complete Order" as complete_order

  usecase "Serve Food" as serve_food

  usecase "Settle the bill" as settle_bill
  usecase "Clean table" as clean_table
}

actor "Kitchen Staff" as ks
actor Waiter as w

' force horizontal ordering: Customer (left) ... staff (right)
c -[hidden]right-> ks
ks -[hidden]-> w

c -> choose_table
choose_table .> view_table

c -> place_order
place_order .> view_menu
view_menu .> scan_qr

c -> track_order

ks -> accept_order
ks -> reject_order
ks -> complete_order

w -> serve_food

c -> settle_bill

w -> clean_table

@enduml